Repository kakao-tech-campus-3rd-step3/Team2_BE, pull requests merged in 2025-09, with the labels that each got.

#7 btsk-7: lint GitHub action 세팅
  .github/workflows/ci.yml
  build.gradle
Labels: feature

#17 btsk-13: 문제집 정보 가져오기
  src/main/java/kr/it/pullit/modules/questionset/domain/entity/Question.java
  src/main/java/kr/it/pullit/modules/questionset/domain/entity/QuestionSet.java
  src/main/java/kr/it/pullit/modules/questionset/repository/QuestionSetRepository.java
  src/main/java/kr/it/pullit/modules/questionset/repository/QuestionSetRepositoryImpl.java
  src/main/java/kr/it/pullit/modules/questionset/repository/adapter/jpa/QuestionSetJpaRepository.java
  src/main/java/kr/it/pullit/modules/questionset/service/QuestionSetService.java
  src/main/java/kr/it/pullit/modules/questionset/web/QuestionSetController.java
  src/main/java/kr/it/pullit/modules/questionset/web/dto/QuestionSetDto.java
Labels: feature

#24 btsk-10: swagger 초기 세팅
  build.gradle
  src/main/java/kr/it/pullit/platform/docs/OpenApiConfig.java
Labels: documentation

#76 btsk-54: 환경변수 리팩토링 environment setting
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  deploy-qa.sh
  docker-compose.qa.yml
  src/main/java/kr/it/pullit/platform/security/config/SecurityConfig.java
  src/main/resources/application-qa.yml
  src/main/resources/application-s3.yml
  src/main/resources/data.sql
  src/test/java/kr/it/pullit/integration/testcontainers/modules/member/web/MemberControllerTest.java
  src/test/java/kr/it/pullit/support/TestContainerTest.java
  src/test/java/kr/it/pullit/support/security/MockAuthenticationFilter.java
  src/test/resources/application-mock-env.yml
  src/test/resources/application-real-env.yml
  src/test/resources/application-testcontainers.yml
Labels: feature, refactor
